FTT-11534 update applicationinsights to latest version
dvsa/azure-logger pull request #41
Opened 2021-08-17 12:37 UTC by ThomasPritchard

- Bumped `applicationinsights` to latest version 2.1.5
- Ran `npm audit fix` to clean the `package-lock.json`

2021-08-17 12:45 UTC, MohammedFoysal requested changes

2021-08-17 12:45 UTC, MohammedFoysal commented on src/config/index.ts
> -  const result = dotenv.config();
I think we should still let dotenv work in the library, just swallow the error instead of throwing

2021-08-17 12:55 UTC, MohammedFoysal approved these changes

2021-08-18 10:05 UTC, premghinde approved these changes

2021-08-18 10:08 UTC, Cavalier07 commented on src/config/index.ts
> +dotenv.config();
This should neverbe used in the code

2021-08-18 10:08 UTC, Cavalier07 commented on src/config/index.ts
> +dotenv.config();
Should only be loaded via npm scripts like we do in the booking app

2021-08-18 10:10 UTC, ThomasPritchard commented on src/config/index.ts
> +dotenv.config();
done

2021-08-18 10:12 UTC, premghinde commented on package.json
>      "dotenv": "8.2.0",
delete ;)

2021-08-18 10:23 UTC, merged